// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrondPlan) DeepCopyInto(out *CrondPlan) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrondPlan.
func (in *CrondPlan) DeepCopy() *CrondPlan {
	if in == nil {
		return nil
	}
	out := new(CrondPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisposablePlan) DeepCopyInto(out *DisposablePlan) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisposablePlan.
func (in *DisposablePlan) DeepCopy() *DisposablePlan {
	if in == nil {
		return nil
	}
	out := new(DisposablePlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoad) DeepCopyInto(out *WorkLoad) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoad.
func (in *WorkLoad) DeepCopy() *WorkLoad {
	if in == nil {
		return nil
	}
	out := new(WorkLoad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadPlan) DeepCopyInto(out *WorkLoadPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadPlan.
func (in *WorkLoadPlan) DeepCopy() *WorkLoadPlan {
	if in == nil {
		return nil
	}
	out := new(WorkLoadPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkLoadPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadPlanList) DeepCopyInto(out *WorkLoadPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkLoadPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadPlanList.
func (in *WorkLoadPlanList) DeepCopy() *WorkLoadPlanList {
	if in == nil {
		return nil
	}
	out := new(WorkLoadPlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkLoadPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadPlanSpec) DeepCopyInto(out *WorkLoadPlanSpec) {
	*out = *in
	if in.Cron != nil {
		in, out := &in.Cron, &out.Cron
		*out = new(CrondPlan)
		**out = **in
	}
	if in.Disposable != nil {
		in, out := &in.Disposable, &out.Disposable
		*out = new(DisposablePlan)
		**out = **in
	}
	if in.WorkLoads != nil {
		in, out := &in.WorkLoads, &out.WorkLoads
		*out = make([]*WorkLoad, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(WorkLoad)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadPlanSpec.
func (in *WorkLoadPlanSpec) DeepCopy() *WorkLoadPlanSpec {
	if in == nil {
		return nil
	}
	out := new(WorkLoadPlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkLoadPlanStatus) DeepCopyInto(out *WorkLoadPlanStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkLoadPlanStatus.
func (in *WorkLoadPlanStatus) DeepCopy() *WorkLoadPlanStatus {
	if in == nil {
		return nil
	}
	out := new(WorkLoadPlanStatus)
	in.DeepCopyInto(out)
	return out
}
