// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/plan/v1.WorkLoadPlan":       schema_pkg_apis_plan_v1_WorkLoadPlan(ref),
		"./pkg/apis/plan/v1.WorkLoadPlanSpec":   schema_pkg_apis_plan_v1_WorkLoadPlanSpec(ref),
		"./pkg/apis/plan/v1.WorkLoadPlanStatus": schema_pkg_apis_plan_v1_WorkLoadPlanStatus(ref),
	}
}

func schema_pkg_apis_plan_v1_WorkLoadPlan(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WorkLoadPlan is the Schema for the workloadplans API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/plan/v1.WorkLoadPlanSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/plan/v1.WorkLoadPlanStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/plan/v1.WorkLoadPlanSpec", "./pkg/apis/plan/v1.WorkLoadPlanStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_plan_v1_WorkLoadPlanSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WorkLoadPlanSpec defines the desired state of WorkLoadPlan",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_plan_v1_WorkLoadPlanStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "WorkLoadPlanStatus defines the observed state of WorkLoadPlan",
				Type:        []string{"object"},
			},
		},
	}
}
