apiVersion: apps/v1
kind: Deployment
metadata:
  name: appplan
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appplan
  template:
    metadata:
      labels:
        name: appplan
    spec:
      serviceAccountName: appplan
      containers:
        - name: appplan
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - appplan
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "appplan"
